# NumPy for Scientific Computing

- How to create and manipulate NumPy arrays.
- Differences between Python lists and NumPy arrays.
- Vectorized operations versus loops.
- Best practices for high-performance code.

Let's get started!


## First, let's import NumPy and create some basic arrays.

In [5]:
import numpy as np

# Create a 1D array (vector) from a Python list
arr1 = np.array([1, 2, 3, 4])
print("arr1 =", arr1)
print("Shape of arr1:", arr1.shape)
print("Data type of arr1:", arr1.dtype)

# Create a 2D array (matrix) from a list of lists
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print("\narr2 =\n", arr2)
print("Shape of arr2:", arr2.shape)
print("Data type of arr2:", arr2.dtype)

# Create an array of all zeros with a given shape
arr3 = np.zeros((2, 3))
print("\narr3 (all zeros) =\n", arr3)

# Create an array of evenly spaced values (like range) 
arr4 = np.arange(0, 10, 2)  # 0 to 8 with step 2
print("\narr4 (even numbers 0-8) =", arr4)


arr1 = [1 2 3 4]
Shape of arr1: (4,)
Data type of arr1: int64

arr2 =
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Data type of arr2: int64

arr3 (all zeros) =
 [[0. 0. 0.]
 [0. 0. 0.]]

arr4 (even numbers 0-8) = [0 2 4 6 8]


## Python lists and NumPy arrays might look similar, but they behave very differently for arithmetic operations.

In [6]:
# Python list vs NumPy array operations
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])

print("py_list * 2 =", py_list * 2)      # List repetition
print("np_array * 2 =", np_array * 2)    # Element-wise multiplication

print("py_list + py_list =", py_list + py_list)   # List concatenation
print("np_array + np_array =", np_array + np_array)  # Element-wise addition

# Note: Adding a scalar to a list is not allowed (it throws an error),
# but adding a scalar to a NumPy array works via broadcasting:
try:
    result = py_list + 3
except Exception as e:
    print("py_list + 3 raises an error:", e)
print("np_array + 3 =", np_array + 3)  # Adds 3 to each element of the array


py_list * 2 = [1, 2, 3, 4, 1, 2, 3, 4]
np_array * 2 = [2 4 6 8]
py_list + py_list = [1, 2, 3, 4, 1, 2, 3, 4]
np_array + np_array = [2 4 6 8]
py_list + 3 raises an error: can only concatenate list (not "int") to list
np_array + 3 = [4 5 6 7]


## NumPy provides many universal functions (ufuncs) that operate element-wise. We can also use broadcasting to work with arrays of different shapes.

In [7]:
# Element-wise operations and math functions
arr = np.array([1, 2, 3, 4, 5])
print("arr =", arr)
print("arr * 3 =", arr * 3)          # multiply each element by 3
print("arr ** 2 =", arr ** 2)        # square of each element (same as np.square(arr))
print("np.sqrt(arr) =", np.sqrt(arr))  # square root of each element

# Aggregation functions
print("sum of arr =", np.sum(arr))      # total of all elements
print("mean of arr =", np.mean(arr))    # average of elements

# Multi-dimensional array aggregation with axis
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nmatrix =\n", matrix)
print("Sum of all elements =", np.sum(matrix))
print("Sum by columns =", np.sum(matrix, axis=0))  # sum of each column
print("Sum by rows =", np.sum(matrix, axis=1))     # sum of each row


arr = [1 2 3 4 5]
arr * 3 = [ 3  6  9 12 15]
arr ** 2 = [ 1  4  9 16 25]
np.sqrt(arr) = [1.         1.41421356 1.73205081 2.         2.23606798]
sum of arr = 15
mean of arr = 3.0

matrix =
 [[1 2 3]
 [4 5 6]]
Sum of all elements = 21
Sum by columns = [5 7 9]
Sum by rows = [ 6 15]


## Learn how to index and slice arrays:

- Access individual elements in 1D and 2D arrays
- Use slicing to extract subarrays
- Apply boolean indexing to filter arrays
- Understand the difference between a view and a copy

Run the accompanying code cell to experiment with these techniques.


In [8]:
# Broadcasting example: add a 1D array to each row of a 2D array
vec = np.array([10, 20, 30])        # shape (3,)
mat = np.array([[1], [2], [3], [4]])  # shape (4,1) - a column vector with 4 rows
#but a better way to create a shape (4,1) is doing:
mat = np.array([1, 2, 3, 4]).reshape(-1, 1)
#the reshape command above is doing a tranformation to the array to make it a column vector, -1 means "as many rows as needed" and 1 means "1 column"
result = mat + vec  # vec is broadcast to shape (4,3) to add to mat
print("vec (shape {}): {}".format(vec.shape, vec))
print("mat (shape {}):\n{}".format(mat.shape, mat))
print("result (shape {}):\n{}".format(result.shape, result))


vec (shape (3,)): [10 20 30]
mat (shape (4, 1)):
[[1]
 [2]
 [3]
 [4]]
result (shape (4, 3)):
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


## Learn how to index and slice arrays:

- Access individual elements in 1D and 2D arrays
- Use slicing to extract subarrays
- Apply boolean indexing to filter arrays
- Understand the difference between a view and a copy

Run the accompanying code cell to experiment with these techniques.


In [ ]:
# 1D array indexing and slicing
arr = np.array([10, 11, 12, 13, 14, 15])
print("arr =", arr)
print("arr[0] =", arr[0])      # first element
print("arr[-1] =", arr[-1])    # last element
print("arr[2:5] =", arr[2:5])  # slice from index 2 to 4 (inclusive)

# Modify a slice (this will affect the original array!)
sub_arr = arr[2:5]    # this is a view of arr
sub_arr[:] = 99       # set all elements in the view to 99
print("After modifying sub_arr, arr =", arr)

# If we need to preserve original, we should copy before modifying
arr_copy = arr.copy()
arr_copy[0:3] = [7, 7, 7]
print("arr_copy after modification =", arr_copy)
print("Original arr remains =", arr)

# 2D array indexing
mat = np.array([[5, 6, 7],
                [8, 9, 10],
                [11, 12, 13]])
print("\nmat =\n", mat)
print("mat[0, 2] =", mat[0, 2])     # element at first row, third column (7)
print("mat[1] (2nd row) =", mat[1]) # second row (index 1), as a 1D array
print("mat[:, 1] =", mat[:, 1])    # second column (all rows in col 1)
print("mat[0:2, 1:3] =\n", mat[0:2, 1:3])  # submatrix: first 2 rows, cols 1-2

# Boolean indexing (masking)
vals = np.array([3, -1, 2, -4, 5, -6])
print("\nvals =", vals)
mask = vals < 0
print("mask for vals < 0 ->", mask)
print("vals[mask] =", vals[mask])   # filter only the negative values


### We can use boolean indexing to modify elements that meet a condition

For example, set all negative values to 0



In [ ]:
#add a mask to modify the negative values of the array and then print
print(vals)

### Indexing cheat-sheet

In [ ]:
# Most Useful Examples of NumPy Array Slicing
import numpy as np

# 1D Array
arr1d = np.array([10, 11, 12, 13, 14, 15])
print("1D array:", arr1d)

# --- BASIC SLICING ---
print("\n--- BASIC SLICING ---")
print("arr1d[0]:", arr1d[0])           # first element
print("arr1d[-1]:", arr1d[-1])         # last element
print("arr1d[1:4]:", arr1d[1:4])       # slice from index 1 to 3
print("arr1d[:3]:", arr1d[:3])         # slice from start to index 2
print("arr1d[3:]:", arr1d[3:])         # slice from index 3 to the end
print("arr1d[::2]:", arr1d[::2])       # slice every 2 steps

# 2D Array
arr2d = np.array([
    [ 1,  2,  3,  4],
    [10, 20, 30, 40],
    [11, 21, 31, 41],
    [12, 22, 32, 42]
])
print("\n2D array:\n", arr2d)

# --- ROW & COLUMN SLICING ---
print("\n--- ROW & COLUMN SLICING ---")
print("arr2d[0, 0]:", arr2d[0, 0])         # element at first row, first column
print("arr2d[1]:", arr2d[1])             # second row (index 1) as a 1D array
print("arr2d[:, 1]:", arr2d[:, 1])       # all rows, second column
print("arr2d[1:3, 1:3]:\n", arr2d[1:3, 1:3])  # subarray from rows 1..2, cols 1..2
print("arr2d[::2, ::2]:\n", arr2d[::2, ::2])  # every 2nd row & col (0,2)

# --- SLICING WITH NEGATIVE INDICES ---
print("\n--- SLICING WITH NEGATIVE INDICES ---")
print("arr2d[-1]:", arr2d[-1])           # last row
print("arr2d[:, -1]:", arr2d[:, -1])     # last column
print("arr2d[-2:, -2:]:\n", arr2d[-2:, -2:])  # bottom-right 2x2 corner

# 3D Array
arr3d = np.arange(2*3*4).reshape(2, 3, 4)
print("\n3D array (shape = {}):\n".format(arr3d.shape), arr3d)

# --- 3D SLICING ---
print("\n--- 3D SLICING ---")
print("arr3d[0, 1, 2]:", arr3d[0, 1, 2])     # single element
print("arr3d[0, 1:, 2:]:\n", arr3d[0, 1:, 2:])  # sub-block
print("arr3d[:, :2, ::2]:\n", arr3d[:, :2, ::2]) # multiple slices across dimensions

# --- BOOLEAN INDEXING ---
# Slicing can also be done using boolean masks (often called boolean indexing).
# For example, filter all values in arr2d that are greater than 20:
mask = arr2d > 20
print("\n--- BOOLEAN INDEXING ---")
print("Mask (arr2d > 20):\n", mask)
print("arr2d[mask]:", arr2d[mask])   # elements where mask is True

# --- VIEW VS COPY ---
# Remember: Slicing usually returns a "view" (not a full copy).
# If you modify the slice, the original array is also modified.
sub_view = arr1d[1:4]
print("\n--- VIEW VS COPY ---")
print("sub_view before:", sub_view)
sub_view[:] = 99
print("sub_view after:", sub_view)
print("arr1d after modifying sub_view:", arr1d)

# If you need an independent copy, do:
arr1d_copy = arr1d[1:4].copy()
arr1d_copy[:] = 7
print("\narr1d_copy (independent):", arr1d_copy)
print("arr1d remains unchanged:", arr1d)


## Comparing performances

- Summing array elements with a Python loop vs. using the vectorized `np.sum`
- Demonstrates the efficiency of NumPy’s built‑in functions with `%timeit`

Run the code cell to observe the performance difference.

In [ ]:
import numpy as np

# Create a large array of 1 million random numbers
N = 1000000
data = np.random.rand(N)

def python_loop_sum(data):
    total = 0.0
    for x in data:
        total += x
    return total

def numpy_vectorized_sum(data):
    return np.sum(data)

# Verify that both methods produce the same result
total_loop = python_loop_sum(data)
total_numpy = numpy_vectorized_sum(data)
print("Sum via loop:", total_loop)
print("Sum via NumPy:", total_numpy)
print("Difference:", abs(total_loop - total_numpy))

# Timing using %timeit
print("\nTiming results:")

print("Python loop sum:")
%timeit python_loop_sum(data)

print("NumPy vectorized sum:")
%timeit numpy_vectorized_sum(data)


## Numpy functions are quite optimized, code using them becomes faster and cleaner!

In [ ]:
import numpy as np

N = 1000000
B = np.random.rand(N) + 0.1  # Add 0.1 to avoid zeros in B.
B[::10] = 0.0  # Introduce zeros in B every 10 elements.
#print(B)
A_res = np.zeros_like(B)
B_res = np.zeros_like(B)

#print(np.power(B, 2, out=A_res, where=(B!=0)))

%timeit -r 20 -n 100  np.power(B, 2, out=A_res, where=(B!=0))
%timeit -r 20 -n 100  B_res[(B!=0)]=B[(B!=0)]**2

# Uncomment to see the results, but change n to a much smaller number
#print("A_res:\n", A_res)
#print("B_res:\n", B_res)

### Common misconception in numpy, find the mistake

In [ ]:
import numpy as np

# Prepopulate V with NaNs
V = np.full(5, np.nan)
A = np.array([2, 0, 5, 0, 10])
condition = A != 0

V = np.divide(10, A, where=condition)
print("Incorrect approach, V becomes:", V)



In [ ]:
# Prepopulate V with NaNs
V = np.full(5, np.nan)
A = np.array([2, 0, 5, 0, 10])
condition = A != 0
#np.power
print("Correct approach, V becomes:", V)

### Why do we see an error message anyway?

using ufuncs is a compromize on more efficient than slicing, but calculating all values anyway.

In [ ]:
import numpy as np

# Create large arrays for the timing comparison.
N = 1000000
A = np.random.rand(N) + 0.1  # Add 0.1 to avoid zeros in A.
B = np.random.rand(N) + 0.1  # Add 0.1 to avoid zeros in B.
print("Min B:", B.min(), "Max B:", B.max())
B[::1000] = 0.0  # Introduce zeros in B every 1000 elements.
print("Number of zeros in B:", np.count_nonzero(B == 0))
print("Min B:", B.min(), "Max B:", B.max())


# -----------------------------------
# Method 1: Using np.divide with out and where
# Prepopulate output array with NaNs.
V_npdivide = np.full_like(A, np.nan)
#np.divide(A, B, out=V_npdivide, where=(B != 0))
#print(V_npdivide)
%timeit -r 20 -n 100  np.divide(A, B, out=V_npdivide, where=(B != 0))

# -----------------------------------
# Method 2: Using normal math operations with a mask.
def masked_divide(A, B):
    V_mask = A
    mask = (B != 0)                    # Create mask to avoid division by zero.    
    C=A[mask] / B[mask]   # Compute division only where safe.
    V_mask[mask] = C
    return V_mask

#V_mask=masked_divide(A, B)
#print(A)

%timeit -r 20 -n 100 masked_divide(A, B)


### There is a common mal pracctice in the code above, can you find it?